export EDITOR=/usr/bin/nvim
export PATH=/usr/local/bin:$HOME/.local/bin:$PATH

# ZSH vars
export ZDOTDIR=~/.config/zsh
export ZSH="/home/garrett/.config/oh-my-zsh"
export HISTFILE=~/.config/zsh/zsh_history

# pyenv
export PYENV_ROOT="$HOME/.config/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
