#          _
#  _______| |__  _ __ ___
# |_  / __| '_ \| '__/ __|
#  / /\__ \ | | | | | (__
# /___|___/_| |_|_|  \___|
#
ZSH_THEME="bira"
ENABLE_CORRECTION="false"

# Plugins
plugins=(
  # defaults
  colored-man-pages
  git
  history-substring-search
  virtualenv
  # custom
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
source $ZDOTDIR/.zsh_aliases
source /home/garrett/.config/broot/launcher/bash/br

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION
