#          _
#  _______| |__  _ __ ___
# |_  / __| '_ \| '__/ __|
#  / /\__ \ | | | | | (__
# /___|___/_| |_|_|  \___|
#
ZSH_THEME="bira"
ENABLE_CORRECTION="true"

# Plugins
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  colored-man-pages
  history-substring-search
  virtualenv
)

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION

source $ZSH/oh-my-zsh.sh
source $ZSH/.sh_aliases
source /home/garrett/.config/broot/launcher/bash/br
