export EDITOR=/usr/bin/nvim
export PATH=/usr/local/bin:$HOME/.local/bin:$PATH

# XDG
export XDG_CONFIG_HOME=$HOME/.config

# ZSH
export ZSH=$XDG_CONFIG_HOME/oh-my-zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export HISTFILE=$ZDOTDIR/zsh_history

# pyenv
export PYENV_ROOT=$XDG_CONFIG_HOME/pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
