version                = 3
final_space            = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  black   = '#262B44'
  blue    = '#4B95E9'
  green   = '#59C9A5'
  orange  = '#F07623'
  red     = '#D81E5B'
  white   = '#E0DEF4'
  yellow  = '#F3AE35'
  magenta = '#CBA6F7'

# Auto upgrade every 168 hours (7 days)
[upgrade]
  source   = 'cdn'
  interval = '168h'
  auto     = true
  notice   = true

[[blocks]]
  type      = 'prompt'
  alignment = 'left'
  newline   = true

  # OS
  [[blocks.segments]]
    type            = 'os'
    style           = 'diamond'
    leading_diamond = ''
    foreground      = 'p:black'
    background      = 'p:white'
    template        = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  # Path
  [[blocks.segments]]
    type             = 'path'
    style            = 'powerline'
    powerline_symbol = ''
    foreground       = 'p:white'
    background       = 'p:blue'
    template         = '  {{ .Path }} '

    [blocks.segments.properties]
      home_icon = '~'
      style     = 'full'

  # Git
  [[blocks.segments]]
    type                 = 'git'
    style                = 'powerline'
    powerline_symbol     = ''
    foreground           = 'p:black'
    background           = 'p:green'
    template             = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', 
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:orange{{ end }}', 
      '{{ if gt .Ahead 0 }}p:blue{{ end }}', '{{ if gt .Behind 0 }}p:green{{ end }}'
    ]

    [blocks.segments.properties]
      branch_icon         = ' '
      fetch_status        = true
      fetch_upstream_icon = true

[[blocks]]
  type      = 'prompt'
  alignment = 'right'

  # Execution Time > 5s
  [[blocks.segments]]
    type             = 'executiontime'
    style            = 'powerline'
    powerline_symbol = ''
    foreground       = 'p:black'
    background       = 'p:yellow'
    invert_powerline = true
    template         = ' {{ .FormattedMs }}  '

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type      = 'prompt'
  alignment = 'left'
  newline   = true

  # Prompt
  [[blocks.segments]]
    type       = 'text'
    style      = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    template   = ''
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}"
    ]

# Prompt overflow
[secondary_prompt]
  foreground = 'p:magenta'
  background = 'transparent'
  template   = ' '

# Transient prompt
[transient_prompt]
  foreground = 'p:magenta'
  background = 'transparent'
  template   = ' '