name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # json linting
  json:
    name: json jsonlint
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint Json
        run: jsonlint **/*.json

  # Markdown linting
  markdown:
    name: Markdown markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install markdown-lint-cli
        run: npm install -g markdownlint-cli
      - name: Lint Markdown
        run: markdownlint **/*.md

  # Shell checks
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Run shellcheck
        run: shellcheck **/*.sh
